export const nigerianStates = [
    "Abia", "Adamawa", "Akwa Ibom", "Anambra", "Bauchi", "Bayelsa", "Benue",
    "Borno", "Cross River", "Delta", "Ebonyi", "Edo", "Ekiti", "Enugu",
    "Gombe", "Imo", "Jigawa", "Kaduna", "Kano", "Katsina", "Kebbi", "Kogi",
    "Kwara", "Lagos", "Nasarawa", "Niger", "Ogun", "Ondo", "Osun", "Oyo",
    "Plateau", "Rivers", "Sokoto", "Taraba", "Yobe", "Zamfara", "Federal Capital Territory (FCT)"
  ];

export const nigerianCitiesByState: Record<string, string[]> = {
  "Abia": ["Aba", "Umuahia", "Ohafia", "Arochukwu", "Bende"],
  "Adamawa": ["Yola", "Mubi", "Jimeta", "Numan", "Ganye"],
  "Akwa Ibom": ["Uyo", "Eket", "Ikot Ekpene", "Oron", "Abak"],
  "Anambra": ["Awka", "Onitsha", "Nnewi", "Ekwulobia", "Ihiala"],
  "Bauchi": ["Bauchi", "Azare", "Misau", "Jama'are", "Katagum"],
  "Bayelsa": ["Yenagoa", "Brass", "Sagbama", "Ogbia", "Nembe"],
  "Benue": ["Makurdi", "Gboko", "Otukpo", "Katsina-Ala", "Vandeikya"],
  "Borno": ["Maiduguri", "Biu", "Bama", "Dikwa", "Monguno"],
  "Cross River": ["Calabar", "Ugep", "Ikom", "Obudu", "Ogoja"],
  "Delta": ["Asaba", "Warri", "Sapele", "Ughelli", "Agbor"],
  "Ebonyi": ["Abakaliki", "Afikpo", "Onueke", "Ezza", "Ikwo"],
  "Edo": ["Benin City", "Auchi", "Ekpoma", "Uromi", "Irrua"],
  "Ekiti": ["Ado-Ekiti", "Ikere-Ekiti", "Efon-Alaaye", "Ijero-Ekiti", "Ikole-Ekiti"],
  "Enugu": ["Enugu", "Nsukka", "Agbani", "Awgu", "Oji River"],
  "Gombe": ["Gombe", "Kumo", "Deba", "Billiri", "Kaltungo"],
  "Imo": ["Owerri", "Orlu", "Okigwe", "Mbaise", "Oguta"],
  "Jigawa": ["Dutse", "Hadejia", "Gumel", "Birnin Kudu", "Kazaure"],
  "Kaduna": ["Kaduna", "Zaria", "Kafanchan", "Kagoro", "Saminaka"],
  "Kano": ["Kano", "Wudil", "Bichi", "Gwarzo", "Rano"],
  "Katsina": ["Katsina", "Daura", "Funtua", "Malumfashi", "Kankia"],
  "Kebbi": ["Birnin Kebbi", "Argungu", "Yauri", "Zuru", "Jega"],
  "Kogi": ["Lokoja", "Okene", "Kabba", "Idah", "Ankpa"],
  "Kwara": ["Ilorin", "Offa", "Omu-Aran", "Jebba", "Lafiagi"],
  "Lagos": ["Ikeja", "Lagos Island", "Epe", "Badagry", "Ikorodu", "Lekki", "Victoria Island", "Surulere", "Yaba"],
  "Nasarawa": ["Lafia", "Keffi", "Akwanga", "Nasarawa", "Doma"],
  "Niger": ["Minna", "Bida", "Kontagora", "Suleja", "Lapai"],
  "Ogun": ["Abeokuta", "Ijebu-Ode", "Sagamu", "Ilaro", "Ota"],
  "Ondo": ["Akure", "Ondo", "Owo", "Ikare", "Ore"],
  "Osun": ["Osogbo", "Ile-Ife", "Ilesa", "Ede", "Iwo"],
  "Oyo": ["Ibadan", "Ogbomosho", "Oyo", "Iseyin", "Saki"],
  "Plateau": ["Jos", "Bukuru", "Pankshin", "Shendam", "Langtang"],
  "Rivers": ["Port Harcourt", "Obio-Akpor", "Eleme", "Okrika", "Bonny"],
  "Sokoto": ["Sokoto", "Gwadabawa", "Tambuwal", "Wurno", "Bodinga"],
  "Taraba": ["Jalingo", "Wukari", "Bali", "Gembu", "Ibi"],
  "Yobe": ["Damaturu", "Potiskum", "Gashua", "Nguru", "Geidam"],
  "Zamfara": ["Gusau", "Kaura Namoda", "Talata Mafara", "Anka", "Maru"],
  "Federal Capital Territory (FCT)": ["Abuja", "Gwagwalada", "Kuje", "Bwari", "Kwali"]
};