export const DialogType = {
    Categories: "Categories",
    PriceInteligence: "PriceInteligence",
    Checklist: "Checklist",
    WorkPlanUpload: "WorkPlanUpload",
    ActivityUpload: "ActivityUpload",
    SspUpload: "SspUpload",
    SspApproveModal: "SspApproveModal",
    SuccessModal: "SuccessModal",
    FundSuccessModal: "FundSuccessModal",
    PreventionModal: "PreventionModal",
    AssestAction: "AssestAction",
    FundRequestModal: "FundRequestModal",
    StateModal: "StateModal",
    FundRequstSummaryModal: "FundRequstSummaryModal",
    StakeholderModal: "StakeholderModal",
    ProjectObjectiveModal: "ProjectObjectiveModal",
    ConsortiumModal: "ConsortiumModal",
    ProjectUploadModal: "ProjectUploadModal",
    ProjectDetailsUploadModal: "ProjectDetailsUploadModal",
    EditUser: "EditUser",
    AssingRoleToUser: "AssingRoleToUser",
    AddPermissionToRole: "AddPermissionToRole",
    SspSubmitModal: "SspSubmitModal",
    AddStock: "AddStock",
    AddTeamMenbers: "AddTeamMenbers",
    ExpenditureModal: "ExpenditureModal",
    ConsultancyApplicationSuccess: "ConsultancyApplicationSuccess",
    SubGrantDocumentUpload: "SubGrantDocumentUpload",
    AddFunfingSource: "AddFunfingSource",
    AddBeneficiaries: "AddBeneficiaries",
    AddDocumentTypes: "AddDocumentTypes",
    AddPartners: "AddPartners",
    AddRiskCategory: "AddRiskCategory",
    AddSupervisionCategory: "AddSupervisionCategory",
    AddFacility: "AddFacility",
    AddAssetConditions: "AddAssetConditions",
    AddAssetTypes: "AddAssetTypes",
    AddCategories: "AddCategories",
    AddDepartments: "AddDepartments",
    AddFinancialYear: "AddFinancialYear",
    AddItems: "AddItems",
    AddLocations: "AddLocations",
    AddLots: "AddLots",
    AddSolicitation: "AddSolicitation",
    AddPrequalificationCategory: "AddPrequalificationCategory",
    AddPrequalificationCriteria: "AddPrequalificationCriteria",
    AddQuestionairs: "AddQuestionairs",
    AddCostCategory: "AddCostCategories",
    AddBudgetLine: "AddBudgetLine",
    AddCostInput: "AddCostInput",
    AddFcoNumber: "AddFcoNumber",
    AddProjectClasses: "AddProjectClasses",
    AddChartsOfAccounts: "AddChartsOfAccounts",
    ProcurementUploadModal: "ProcurementUploadModal",
    HrSuccessModal: "HrSuccessModal",
    ApprovalModal: "ApprovalModal",
    FeedbackModal: "FeedbackModal",
    ActivityTrackerModal: "ActivityTrackerModal",
    AddNewRoleModal: "AddNewRoleModal",
    AddSupervisionCriteria: "AddSupervisionCriteria",
    FundRequestBreakdown: "FundRequestBreakdown",
    ChangeRiskStatusModal: "ChangeRiskStatusModal",
    ChangeProjectStatusModal: "ChangeProjectStatusModal",
    AddPosition: "AddPosition",
};

export const largeDailogScreen = {
    width: "max-w-6xl",
    height: "max-h-[700px]",
};

export const mediumDailogScreen = {
    width: "max-w-2xl",
    height: "max-h-[700px]",
};

// max-w-6xl max-h-[700px]
