export const RouteEnum = {
  DASHBOARD: "/",
  OVERVIEW: "/procurement-management/overview",
  EOI: "/procurement-management/eoi",
  EOI_VENDOR: "/procurement-management/eoi-vendor",
  COMPETITIVE_ANALYSIS: "/procurement-management/competitive-analysis",
  PAYMENT_REQUEST: "/procurement-management/payment-request",
  PURCHASE_REQUEST: "/procurement-management/purchase-request",
  PROCUREMENT_PLAN: "/procurement-management/procurement-plan",
  PROCUREMENT_PLAN_TRACKER: "/procurement-management/procurement-plan-tracker",
  REPORT: "/procurement-management/report",
  RFQ: "/procurement-management/rfq",
  RFQ_VENDOR: "/procurement-management/rfq-vendor",
  VENDOR_MANAGEMENT: "/procurement-management/vendor-management",
  //program routes
  PROGRAM_OVERVIEW: "/program/overview",
  WORK_PLAN: "/program/work-plan",
  WORK_PLAN_AUDIT: "/program/work-plan-audit",
  DONOR_MANAGEMENT: "/program/donor-management",
  PROJECTS: "/program/projects",
  TRAINING: "/program/training-and-procurement",
  PROGRAM_PAYMENT_REQUEST: "/program/payment-request",
  PROGRAM_REPORT: "/program/report",
  // PROGRAM_OVERVIEW: "/program/overview",
  // PROGRAM_OVERVIEW: "/program/overview",
};
