"use client";

import { useMemo } from "react";
import Card from "@/components/Card";
import { useGetAllFundRequests } from "@/features/programs/controllers/fundRequestController";
import { LoadingSpinner } from "@/components/Loading";
import { Button } from "@/components/ui/button";
import { Download, Printer, ArrowLeft } from "lucide-react";
import { useRouter } from "next/navigation";
import logoPng from "assets/imgs/logo.png";

export default function FundRequestLocationSummary() {
  const router = useRouter();

  // Fetch ALL fund requests
  const { data: fundRequestsData, isLoading } = useGetAllFundRequests({
    page: 1,
    size: 10000, // Get all
  });

  const fundRequests = fundRequestsData?.data?.results || [];

  // Group fund requests by location
  const locationSummary = useMemo(() => {
    const grouped: Record<string, {
      locationName: string;
      requests: any[];
      totalAmount: number;
      uniqueIds: string[];
      currency: string;
    }> = {};

    fundRequests.forEach((request: any) => {
      const locationName = typeof request.location === 'object'
        ? request.location.name
        : request.location || 'Unknown Location';

      if (!grouped[locationName]) {
        grouped[locationName] = {
          locationName,
          requests: [],
          totalAmount: 0,
          uniqueIds: [],
          currency: request.currency || 'NGN',
        };
      }

      grouped[locationName].requests.push(request);
      grouped[locationName].totalAmount += Number(request.total_amount || 0);
      if (request.uuid_code) {
        grouped[locationName].uniqueIds.push(request.uuid_code);
      }
    });

    return Object.values(grouped);
  }, [fundRequests]);

  const grandTotal = useMemo(() => {
    return locationSummary.reduce((sum, loc) => sum + loc.totalAmount, 0);
  }, [locationSummary]);

  const handlePrint = () => {
    window.print();
  };

  const handleDownload = () => {
    const fileName = `fund-request-location-summary-${new Date().toISOString().split('T')[0]}.txt`;

    const content = `
ACHIEVING HEALTH NIGERIA INITIATIVE (AHNI)
FUND REQUEST SUMMARY BY LOCATION

Generated on: ${new Date().toLocaleDateString()} ${new Date().toLocaleTimeString()}

=====================================
LOCATION SUMMARY
=====================================

${locationSummary.map((loc, index) => `
${index + 1}. ${loc.locationName}
   Total Amount: ${loc.currency === 'NGN' ? '₦' : '$'}${loc.totalAmount.toLocaleString('en-US', { minimumFractionDigits: 2 })}
   Number of Requests: ${loc.requests.length}
   Unique IDs: ${loc.uniqueIds.join(', ')}
`).join('')}

=====================================
GRAND TOTAL: ${locationSummary[0]?.currency === 'NGN' ? '₦' : '$'}${grandTotal.toLocaleString('en-US', { minimumFractionDigits: 2 })}
=====================================

Report generated by AHNI Fund Request System
    `.trim();

    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = fileName;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  if (isLoading) {
    return <LoadingSpinner />;
  }

  const currency = locationSummary[0]?.currency || 'NGN';
  const currencySymbol = currency === 'NGN' ? '₦' : '$';

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between no-print">
        <div className="flex items-center gap-4">
          <Button
            variant="outline"
            size="sm"
            onClick={() => router.back()}
          >
            <ArrowLeft className="w-4 h-4 mr-2" />
            Back
          </Button>
          <div>
            <h1 className="text-2xl font-bold">Fund Request Summary by Location</h1>
            <p className="text-sm text-gray-600">
              {locationSummary.length} Locations • {fundRequests.length} Total Requests
            </p>
          </div>
        </div>
        <div className="flex gap-2">
          <Button variant="outline" onClick={handleDownload}>
            <Download className="w-4 h-4 mr-2" />
            Download
          </Button>
          <Button variant="outline" onClick={handlePrint}>
            <Printer className="w-4 h-4 mr-2" />
            Print
          </Button>
        </div>
      </div>

      {/* Printable Content */}
      <Card className="p-8 print-content">
        {/* Logo and Header */}
        <div className="flex flex-col items-center mb-8">
          <img src={(logoPng as any).src || logoPng} alt="AHNI Logo" width={120} className="mb-4" />
          <h1 className="text-xl font-bold">Achieving Health Nigeria Initiative (AHNI)</h1>
          <h2 className="text-lg font-semibold text-gray-700 mt-2">Fund Request Summary</h2>
        </div>

        {/* Summary Table */}
        <div className="overflow-x-auto">
          <h3 className="text-center font-bold text-lg mb-4 bg-gray-100 py-2">
            Fund Request Summary
          </h3>

          <table className="w-full border-collapse border-2 border-gray-800">
            <thead>
              <tr className="bg-gray-100">
                <th className="border-2 border-gray-800 p-3 text-left font-bold">S/N</th>
                <th className="border-2 border-gray-800 p-3 text-left font-bold">Description of Activity</th>
                <th className="border-2 border-gray-800 p-3 text-right font-bold">
                  Fund Request<br />for this period
                </th>
                <th className="border-2 border-gray-800 p-3 text-left font-bold">Unique Identifier Code</th>
              </tr>
            </thead>
            <tbody>
              {locationSummary.length > 0 ? (
                locationSummary.map((location, index) => (
                  <tr key={index}>
                    <td className="border-2 border-gray-800 p-3 font-semibold">
                      {index + 1}.0
                    </td>
                    <td className="border-2 border-gray-800 p-3 font-bold">
                      {location.locationName}
                    </td>
                    <td className="border-2 border-gray-800 p-3 text-right">
                      {location.totalAmount.toLocaleString('en-US', {
                        minimumFractionDigits: 2,
                        maximumFractionDigits: 2
                      })}
                    </td>
                    <td className="border-2 border-gray-800 p-3 font-bold">
                      {location.uniqueIds.join(', ') || 'N/A'}
                    </td>
                  </tr>
                ))
              ) : (
                <tr>
                  <td colSpan={4} className="border-2 border-gray-800 p-8 text-center text-gray-500">
                    No fund requests found
                  </td>
                </tr>
              )}

              {/* Grand Total Row */}
              <tr className="bg-gray-100 font-bold">
                <td colSpan={2} className="border-2 border-gray-800 p-3 text-center text-lg">
                  GRAND TOTAL
                </td>
                <td className="border-2 border-gray-800 p-3 text-right text-lg">
                  {grandTotal.toLocaleString('en-US', {
                    minimumFractionDigits: 2,
                    maximumFractionDigits: 2
                  })}
                </td>
                <td className="border-2 border-gray-800 p-3"></td>
              </tr>

              {/* Check Row */}
              <tr>
                <td colSpan={2} className="border-2 border-gray-800 p-3 text-right font-bold">
                  Check
                </td>
                <td className="border-2 border-gray-800 p-3 text-right">
                  {grandTotal.toLocaleString('en-US', {
                    minimumFractionDigits: 2,
                    maximumFractionDigits: 2
                  })}
                </td>
                <td className="border-2 border-gray-800 p-3 text-center font-bold">
                  TRUE
                </td>
              </tr>
            </tbody>
          </table>
        </div>

        {/* Additional Information */}
        <div className="mt-8 space-y-6">
          {/* General Comment/Recommendation */}
          <div className="border-2 border-gray-800 p-4">
            <h4 className="font-bold text-center mb-4">General Comment/Recommendation</h4>
            <div className="space-y-3">
              <div className="grid grid-cols-3 gap-4">
                <div className="font-bold">7.0</div>
                <div className="font-bold">TOTAL FUND REQUEST</div>
                <div className="text-right font-semibold">
                  {grandTotal.toLocaleString('en-US', {
                    minimumFractionDigits: 2,
                    maximumFractionDigits: 2
                  })}
                </div>
              </div>
              <div className="grid grid-cols-3 gap-4">
                <div className="font-bold">8.0</div>
                <div className="font-bold">BALANCE ON HAND</div>
                <div className="text-right font-semibold">
                  {/* Calculate total balance */}
                  {locationSummary
                    .reduce((sum, loc) => {
                      const locBalance = loc.requests.reduce((s, r) => s + Number(r.available_balance || 0), 0);
                      return sum + locBalance;
                    }, 0)
                    .toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}
                </div>
              </div>
              <div className="grid grid-cols-3 gap-4">
                <div className="font-bold">9.0</div>
                <div className="font-bold">AMOUNT DUE TO ACE HEAD OFFICE</div>
                <div className="text-right font-semibold">
                  {grandTotal.toLocaleString('en-US', {
                    minimumFractionDigits: 2,
                    maximumFractionDigits: 2
                  })}
                </div>
              </div>
            </div>
          </div>

          {/* AHNI Head Office Authorization */}
          <div className="border-2 border-gray-800">
            <div className="bg-gray-100 text-center font-bold py-2 border-b-2 border-gray-800">
              AHNI HEAD OFFICE AUTHORISATION
            </div>
            <div className="grid grid-cols-3">
              <div className="border-r-2 border-gray-800 p-4">
                <p className="font-bold mb-2">Prepared By:</p>
                <p className="text-sm mb-4">Rosita Adunchezor</p>
                <p className="font-bold mt-8">Sign & Date:</p>
                <div className="h-16 mt-2"></div>
              </div>
              <div className="border-r-2 border-gray-800 p-4">
                <p className="font-bold mb-2">Reviewed By:</p>
                <p className="text-sm mb-4">LEX</p>
                <p className="font-bold mt-8">Sign & Date:</p>
                <div className="h-16 mt-2"></div>
              </div>
              <div className="p-4">
                <p className="font-bold mb-2">Authorised By:</p>
                <p className="text-sm mb-4"></p>
                <p className="font-bold mt-8">Sign & Date:</p>
                <div className="h-16 mt-2"></div>
              </div>
            </div>
          </div>
        </div>

        {/* Footer */}
        <div className="mt-8 text-center text-sm text-gray-600">
          <p>Generated by AHNI Fund Request System</p>
          <p>{new Date().toLocaleDateString()} {new Date().toLocaleTimeString()}</p>
        </div>
      </Card>

      {/* Print Styles */}
      <style jsx global>{`
        @media print {
          .no-print {
            display: none !important;
          }
          .print-content {
            box-shadow: none !important;
            margin: 0 !important;
            padding: 20px !important;
          }
          body {
            margin: 0;
            padding: 0;
          }
        }
      `}</style>
    </div>
  );
}
