export interface JobAdvertisement {
  id?: string; // Optional since it's generated by the backend
  advert_document: string;
  title: string;
  grade_level: string;
  locations: string;
  job_type: "Internal" | "External" | "Both"; // Assuming it's one of these values
  duration: string;
  commencement_date: string;
  number_of_positions: number;
  supervisor: string;
  any_other_info: string;
  background: string;
  created_at?: string;
  updated_at?: string;
}
